/*
================================================================================
Database Console Pages Generator (SQLPage + Spry Schema Introspection)
================================================================================

This script populates the `sqlpage_files` virtual filesystem with a complete
set of SQLPage UI pages that form an interactive “Database Console” for any
SQLite database. All pages are stored inside SQLite itself and rendered by
SQLPage at runtime.

The workflow is:

1. Create the top-level console index page.
   Provides entry points for exploring the information schema and browsing
   table/view content.

2. Create the Information Schema browser.
   Uses the JSON schema snapshot (spry.d/info-schema.auto.json) generated by
   spry-schema-info.sqlite.sql. Lists all tables and views with links to
   detail pages.

3. Create detail pages for each table.
   Includes columns, foreign keys, indexes, and the original CREATE TABLE SQL.
   Data is sourced from the spry_schema_info_* relational projection views.

4. Create detail pages for each view.
   Similar to table pages, displaying columns (if present) and CREATE VIEW SQL.

5. Create a content index.
   Lists all auto-generated content pages for tables and views. These pages
   show live data rows with sortable/searchable tables.

6. Auto-generate content pages for every table.
   Each table gets a `.auto.sql` page with pagination logic using SQLPage
   variables. Rows are displayed directly from the underlying table.

7. Auto-generate content pages for every view.
   Same idea as table content pages, but using simplified limit/offset
   pagination.

Overall purpose:
- Provide a turn-key, self-contained console UI for browsing a database.
- Require no external files; everything is stored inside `sqlpage_files`.
- Use Spry's schema introspection JSON + projection views to dynamically
  generate links, metadata, and table/view listings.
================================================================================
*/

-- pages are idempotent
DELETE FROM sqlpage_files WHERE path LIKE 'console/%';

INSERT OR REPLACE INTO sqlpage_files (path, contents, last_modified)
VALUES (
  'console/index.sql',
  'SELECT ''title'' AS component, ''Database Console'' AS contents;

SELECT ''breadcrumb'' AS component;
SELECT ''Database Console'' AS title, TRUE AS active;

SELECT ''list'' AS component;
SELECT ''Information Schema'' AS title,
       ''Browse tables, views, and relationships'' AS description,
       ''info-schema/index.sql'' AS link;
SELECT ''Table and View Content'' AS title,
       ''Browse rows in tables and views via auto-generated pages'' AS description,
       ''content/index.sql'' AS link;',
  datetime('now')
);

-- Information schema hub: lists all tables and views
INSERT OR REPLACE INTO sqlpage_files (path, contents, last_modified)
VALUES (
  'console/info-schema/index.sql',
  'SELECT ''title'' AS component, ''Information Schema'' AS contents;

SELECT ''breadcrumb'' AS component;
SELECT ''Database Console'' AS title, ''../index.sql'' AS link;
SELECT ''Information Schema'' AS title, TRUE AS active;

SELECT ''title'' AS component, ''Tables'' AS contents;
SELECT ''table'' AS component,
       ''Table'' AS markdown,
       ''Column Count'' AS align_right,
       ''Content'' AS markdown,
       TRUE AS sort,
       TRUE AS search;
SELECT
  ''['' || table_name || ''](table.sql?name='' || table_name || '')'' AS "Table",
  ncol AS "Column Count",
  ''[Content](../content/table/'' || table_name || ''.auto.sql)'' AS "Content"
FROM spry_schema_info_table
ORDER BY table_name;

SELECT ''title'' AS component, ''Views'' AS contents;
SELECT ''table'' AS component,
       ''View'' AS markdown,
       ''Column Count'' AS align_right,
       ''Content'' AS markdown,
       TRUE AS sort,
       TRUE AS search;
SELECT
  ''['' || vj.key || ''](view.sql?name='' || vj.key || '')'' AS "View",
  CAST(json_extract(vj.value,''$.ncol'') AS INTEGER) AS "Column Count",
  ''[Content](../content/view/'' || vj.key || ''.auto.sql)'' AS "Content"
FROM sqlpage_files AS s,
     json_each(s.contents, ''$.views'') AS vj
WHERE s.path = ''spry.d/info-schema.auto.json''
ORDER BY vj.key;',
  datetime('now')
);

-- Table detail page: columns, foreign keys, indexes, and CREATE TABLE
INSERT OR REPLACE INTO sqlpage_files (path, contents, last_modified)
VALUES (
  'console/info-schema/table.sql',
  'SELECT ''title'' AS component, $name AS contents;

SELECT ''breadcrumb'' AS component;
SELECT ''Database Console'' AS title, ''../index.sql'' AS link;
SELECT ''Information Schema'' AS title, ''index.sql'' AS link;
SELECT $name AS title, TRUE AS active;

SELECT ''table'' AS component;
SELECT
  column_name AS "Column",
  column_type AS "Type",
  CASE CAST(not_null AS INTEGER) WHEN 1 THEN ''Yes'' ELSE ''No'' END AS "Not Null",
  CASE CAST(part_of_pk AS INTEGER) WHEN 0 THEN ''No'' ELSE ''Yes'' END AS "Primary Key",
  dflt_value AS "Default"
FROM spry_schema_info_table_column
WHERE table_name = $name
ORDER BY cid;

SELECT ''title'' AS component, ''Foreign Keys'' AS contents, 2 AS level;
SELECT ''table'' AS component;
SELECT
  from_column AS "From Column",
  ref_table   AS "References Table",
  to_column   AS "References Column",
  on_update   AS "On Update",
  on_delete   AS "On Delete",
  match       AS "Match"
FROM spry_schema_info_foreign_key
WHERE table_name = $name
ORDER BY fk_id, seq;

SELECT ''title'' AS component, ''Indexes'' AS contents, 2 AS level;
SELECT ''table'' AS component;
SELECT
  index_name AS "Index Name",
  origin     AS "Origin",
  CASE CAST(is_unique AS INTEGER) WHEN 1 THEN ''Yes'' ELSE ''No'' END AS "Unique",
  CASE CAST(is_partial AS INTEGER) WHEN 1 THEN ''Yes'' ELSE ''No'' END AS "Partial",
  definition_sql AS "Definition SQL"
FROM spry_schema_info_index
WHERE table_name = $name
ORDER BY index_name;

SELECT ''title'' AS component, ''Table SQL'' AS contents, 2 AS level;
SELECT ''code'' AS component;
SELECT
  ''sql'' AS language,
  (SELECT definition_sql FROM spry_schema_info_table WHERE table_name = $name) as contents;',
  datetime('now')
);

-- View detail page: columns (if available) and CREATE VIEW
INSERT OR REPLACE INTO sqlpage_files (path, contents, last_modified)
VALUES (
  'console/info-schema/view.sql',
  'SELECT ''title'' AS component, $name AS contents;

SELECT ''breadcrumb'' AS component;
SELECT ''Database Console'' AS title, ''../index.sql'' AS link;
SELECT ''Information Schema'' AS title, ''index.sql'' AS link;
SELECT $name AS title, TRUE AS active;

SELECT ''table'' AS component;
SELECT
  column_name AS "Column",
  column_type AS "Type",
  CASE CAST(not_null AS INTEGER) WHEN 1 THEN ''Yes'' ELSE ''No'' END AS "Not Null",
  dflt_value AS "Default"
FROM spry_schema_info_view_column
WHERE view_name = $name
ORDER BY cid;

SELECT ''title'' AS component, ''View SQL'' AS contents, 2 AS level;
SELECT ''code'' AS component;
SELECT
  ''sql'' AS language,
  definition_sql AS contents
FROM spry_schema_info_view
WHERE view_name = $name;',
  datetime('now')
);

-- Content index: lists all auto-generated table/view content pages
INSERT OR REPLACE INTO sqlpage_files (path, contents, last_modified)
VALUES (
  'console/content/index.sql',
  'SELECT ''title'' AS component, ''SQLPage Content Browser'' AS contents;

SELECT ''breadcrumb'' AS component;
SELECT ''Database Console'' AS title, ''../index.sql'' AS link;
SELECT ''Table and View Content'' AS title, TRUE AS active;

SELECT ''text'' AS component,
       ''- Auto-generated `.auto.sql` pages provide default content views for each table and view.\n''
       || ''- You can create a companion `.sql` page with the same prefix to override any default.'' AS contents_md;

SELECT ''title'' AS component, ''Tables'' AS contents, 2 AS level;
SELECT ''table'' AS component,
       ''Table'' AS markdown,
       ''Column Count'' as align_right,
       ''Schema'' AS markdown,
       TRUE AS sort,
       TRUE AS search;
SELECT
  ''['' || table_name || ''](table/'' || table_name || ''.auto.sql)'' AS "Table",
  ncol AS "Column Count",
  ''[Schema](../info-schema/table.sql?name='' || table_name || '')'' AS "Schema"
FROM spry_schema_info_table
ORDER BY table_name;

SELECT ''title'' AS component, ''Views'' AS contents, 2 AS level;
SELECT ''table'' AS component,
       ''View'' AS markdown,
       ''Column Count'' as align_right,
       ''Schema'' AS markdown,
       TRUE AS sort,
       TRUE AS search;
SELECT
  ''['' || vj.key || ''](view/'' || vj.key || ''.auto.sql)'' AS "View",
  CAST(json_extract(vj.value,''$.ncol'') AS INTEGER) AS "Column Count",
  ''[Schema](../info-schema/view.sql?name='' || vj.key || '')'' AS "Schema"
FROM sqlpage_files AS s,
     json_each(s.contents, ''$.views'') AS vj
WHERE s.path = ''spry.d/info-schema.auto.json''
ORDER BY vj.key;
',
  datetime('now')
);

-- Auto-generated TABLE content pages: one per table (pagination done per SQLPage tutorial)
INSERT OR REPLACE INTO sqlpage_files (path, contents, last_modified)
SELECT
  'console/content/table/' || table_name || '.auto.sql' AS path,
  'SELECT ''title'' AS component, ''' || table_name || ' (table rows)'' AS contents;

SELECT ''breadcrumb'' AS component;
SELECT ''Database Console'' AS title, ''../../index.sql'' AS link;
SELECT ''Table and View Content'' AS title, ''../index.sql'' AS link;
SELECT ''' || table_name || ''' AS title, TRUE AS active;

-- Pagination constants
SET MAX_RECORD_PER_PAGE = COALESCE(CAST($limit AS INTEGER), 50);
SET MAX_PAGES = 10;

-- Total rows
SET records_count = (SELECT COUNT(*) FROM "' || replace(table_name, '"', '""') || '");

-- Total pages (ceil(records_count / MAX_RECORD_PER_PAGE))
SET pages_count = (CAST($records_count AS INTEGER) / CAST($MAX_RECORD_PER_PAGE AS INTEGER));
SET pages_count = (
  CASE
    WHEN CAST($records_count AS INTEGER) = 0 THEN 1
    WHEN MOD(CAST($records_count AS INTEGER), CAST($MAX_RECORD_PER_PAGE AS INTEGER)) = 0 THEN $pages_count
    ELSE (CAST($pages_count AS INTEGER) + 1)
  END
);

-- Current page and index (from URL)
SET page = COALESCE(CAST($page AS INTEGER), 1);
SET idx_page = COALESCE(CAST($idx_page AS INTEGER), 1);

-- Clamp page into [1, pages_count]
SET page = (
  CASE
    WHEN $page < 1 THEN 1
    WHEN $page > $pages_count THEN $pages_count
    ELSE $page
  END
);

-- Data table
SELECT ''table'' AS component, TRUE AS sort, TRUE AS search;
SELECT *
FROM "' || replace(table_name, '"', '""') || '"
LIMIT CAST($MAX_RECORD_PER_PAGE AS INTEGER)
OFFSET (CAST($page AS INTEGER) - 1) * CAST($MAX_RECORD_PER_PAGE AS INTEGER);

-- Previous/next parameter objects
SET previous_parameters = (
  CASE
    WHEN CAST($page AS INTEGER) > 1 THEN
      json_object(
        ''page'', (CAST($page AS INTEGER) - 1),
        ''idx_page'', (CASE
          WHEN CAST($idx_page AS INTEGER) > 1 THEN (CAST($idx_page AS INTEGER) - 1)
          ELSE $idx_page
        END),
        ''limit'', $MAX_RECORD_PER_PAGE
      )
    ELSE json_object(''page'', 1, ''idx_page'', 1, ''limit'', $MAX_RECORD_PER_PAGE)
  END
);

SET next_parameters = (
  CASE
    WHEN CAST($page AS INTEGER) < CAST($pages_count AS INTEGER) THEN
      json_object(
        ''page'', (CAST($page AS INTEGER) + 1),
        ''idx_page'', (CASE
          WHEN CAST($idx_page AS INTEGER) < (CAST($pages_count AS INTEGER) - CAST($MAX_PAGES AS INTEGER) + 1)
            THEN (CAST($idx_page AS INTEGER) + 1)
          ELSE $idx_page
        END),
        ''limit'', $MAX_RECORD_PER_PAGE
      )
    ELSE json_object(''page'', $pages_count, ''idx_page'', $idx_page, ''limit'', $MAX_RECORD_PER_PAGE)
  END
);

-- Pagination component (buttons)
SELECT
  ''pagination'' AS component,
  (CAST($page AS INTEGER) = 1) AS first_disabled,
  (CAST($page AS INTEGER) = 1) AS previous_disabled,
  (CAST($page AS INTEGER) = CAST($pages_count AS INTEGER)) AS next_disabled,
  (CAST($page AS INTEGER) = CAST($pages_count AS INTEGER)) AS last_disabled,
  sqlpage.link(sqlpage.path(), json_object(''page'', 1, ''idx_page'', 1, ''limit'', $MAX_RECORD_PER_PAGE)) AS first_link,
  sqlpage.link(sqlpage.path(), $previous_parameters) AS previous_link,
  sqlpage.link(sqlpage.path(), $next_parameters) AS next_link,
  sqlpage.link(
    sqlpage.path(),
    json_object(
      ''page'', $pages_count,
      ''idx_page'', (CASE
        WHEN (CAST($pages_count AS INTEGER) <= CAST($MAX_PAGES AS INTEGER)) THEN 1
        ELSE (CAST($pages_count AS INTEGER) - CAST($MAX_PAGES AS INTEGER) + 1)
      END),
      ''limit'', $MAX_RECORD_PER_PAGE
    )
  ) AS last_link,
  TRUE AS outline;

-- Page numbers
WITH RECURSIVE page_numbers AS (
  SELECT CAST($idx_page AS INTEGER) AS number
  UNION ALL
  SELECT number + 1
  FROM page_numbers
  LIMIT CAST($MAX_PAGES AS INTEGER)
)
SELECT
  number AS contents,
  sqlpage.link(sqlpage.path(), json_object(''page'', number, ''idx_page'', $idx_page, ''limit'', $MAX_RECORD_PER_PAGE)) AS link,
  (number = CAST($page AS INTEGER)) AS active
FROM page_numbers
WHERE number <= CAST($pages_count AS INTEGER);' AS contents,
  datetime('now')
FROM spry_schema_info_table;

-- Auto-generated VIEW content pages: one per view (with pagination component)
INSERT OR REPLACE INTO sqlpage_files (path, contents, last_modified)
SELECT
  'console/content/view/' || view_name || '.auto.sql' AS path,
  'SELECT ''title'' AS component, ''' || view_name || ' (view rows)'' AS contents;

SELECT ''breadcrumb'' AS component;
SELECT ''Database Console'' AS title, ''../../index.sql'' AS link;
SELECT ''Table and View Content'' AS title, ''../index.sql'' AS link;
SELECT ''' || view_name || ''' AS title, TRUE AS active;

-- Normalize pagination inputs
SET limit  = COALESCE(CAST($limit  AS INTEGER), 50);
SET offset = COALESCE(CAST($offset AS INTEGER), 0);

-- Total rows for pagination
SET records_count = (SELECT COUNT(*) FROM "' || replace(view_name, '"', '""') || '");

-- Data table
SELECT ''table'' AS component, TRUE AS sort, TRUE AS search;
SELECT *
FROM "' || replace(view_name, '"', '""') || '"
LIMIT $limit
OFFSET $offset;

-- Pagination control
SELECT ''pagination'' AS component;
WITH RECURSIVE pages(off) AS (
  SELECT 0
  UNION ALL
  SELECT off + $limit
  FROM pages
  WHERE off + $limit < $records_count
)
SELECT
  (off / $limit) + 1 AS contents,
  sqlpage.link(
    sqlpage.path(),
    json_object(''limit'', $limit, ''offset'', off)
  ) AS link,
  off = $offset AS active
FROM pages;' AS contents,
  datetime('now')
FROM spry_schema_info_view;

